apiVersion: v1
kind: Namespace
metadata:
  name: clos-analytics
  labels:
    name: clos-analytics
    app.kubernetes.io/name: clos-analytics
    app.kubernetes.io/part-of: candlefish-ai
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: clos-analytics-quota
  namespace: clos-analytics
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "10"
    services.loadbalancers: "2"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: clos-analytics-limits
  namespace: clos-analytics
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container