apiVersion: apps/v1
kind: Deployment
metadata:
  name: clos-websocket
  namespace: clos-analytics
  labels:
    app: clos-websocket
    component: realtime
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: clos-websocket
  template:
    metadata:
      labels:
        app: clos-websocket
        component: realtime
    spec:
      serviceAccountName: clos-analytics-sa
      securityContext:
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: clos-websocket
        image: candlefish/clos-websocket:latest
        ports:
        - containerPort: 8001
          name: websocket
        env:
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: clos-analytics-config
              key: NODE_ENV
        - name: PORT
          value: "8001"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: clos-analytics-secrets
              key: REDIS_URL
        - name: WS_HEARTBEAT_INTERVAL
          valueFrom:
            configMapKeyRef:
              name: clos-analytics-config
              key: WS_HEARTBEAT_INTERVAL
        - name: WS_MAX_CONNECTIONS
          valueFrom:
            configMapKeyRef:
              name: clos-analytics-config
              key: WS_MAX_CONNECTIONS
        - name: ANALYTICS_EVENTS_BUFFER_SIZE
          valueFrom:
            configMapKeyRef:
              name: clos-analytics-config
              key: ANALYTICS_EVENTS_BUFFER_SIZE
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: clos-analytics-config
              key: LOG_LEVEL
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 10"]
      terminationGracePeriodSeconds: 20
      imagePullSecrets:
      - name: docker-registry-secret

---
apiVersion: v1
kind: Service
metadata:
  name: clos-websocket-service
  namespace: clos-analytics
  labels:
    app: clos-websocket
    component: realtime
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  ports:
  - port: 8001
    targetPort: 8001
    name: websocket
    protocol: TCP
  selector:
    app: clos-websocket
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: clos-websocket-hpa
  namespace: clos-analytics
  labels:
    app: clos-websocket
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: clos-websocket
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 15
      - type: Pods
        value: 1
        periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60