# Prometheus alert rules for candlefish.ai infrastructure
groups:
  - name: candlefish.alerts
    rules:
      # Service availability alerts
      - alert: ServiceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.instance }} is down"
          description: "{{ $labels.instance }} has been down for more than 5 minutes."

      - alert: HighErrorRate
        expr: rate(nginx_http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High error rate on {{ $labels.instance }}"
          description: "Error rate is {{ $value }} errors per second on {{ $labels.instance }}"

      # SSL certificate alerts
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate for {{ $labels.instance }} expires in {{ $value }} days"

      - alert: SSLCertificateExpired
        expr: ssl_certificate_expiry_seconds - time() <= 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: "SSL certificate expired"
          description: "SSL certificate for {{ $labels.instance }} has expired"

      # DNS resolution alerts  
      - alert: DNSResolutionFailed
        expr: probe_success{job="blackbox-dns"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "DNS resolution failed for {{ $labels.instance }}"
          description: "DNS resolution has been failing for {{ $labels.instance }} for more than 5 minutes"

      # HTTP health check alerts
      - alert: HTTPHealthCheckFailed
        expr: probe_success{job="blackbox-http"} == 0
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "HTTP health check failed for {{ $labels.instance }}"
          description: "HTTP health check has been failing for {{ $labels.instance }} for more than 3 minutes"

      # Response time alerts
      - alert: HighResponseTime
        expr: probe_http_duration_seconds{job="blackbox-http"} > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time on {{ $labels.instance }}"
          description: "Response time is {{ $value }}s on {{ $labels.instance }}"

      # System resource alerts
      - alert: HighCPUUsage
        expr: (100 - (avg by (instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage on {{ $labels.instance }}"
          description: "CPU usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage on {{ $labels.instance }}"
          description: "Memory usage is {{ $value }}% on {{ $labels.instance }}"

      - alert: DiskSpaceLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 15
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Low disk space on {{ $labels.instance }}"
          description: "Disk space is {{ $value }}% full on {{ $labels.instance }}"

      # Nginx specific alerts
      - alert: NginxHighConnectionCount
        expr: nginx_connections_active > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High active connection count on Nginx"
          description: "Active connections: {{ $value }}"

      # Rate limiting alerts
      - alert: HighRateLimitHits
        expr: increase(nginx_http_requests_total{status="429"}[5m]) > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High rate limit hits"
          description: "{{ $value }} rate limit hits in the last 5 minutes"

  - name: candlefish.database
    rules:
      # Redis alerts (if used)
      - alert: RedisDown
        expr: redis_up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis instance {{ $labels.instance }} is down"

      # PostgreSQL alerts (if used)
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL instance {{ $labels.instance }} is down"

      - alert: PostgreSQLTooManyConnections
        expr: sum by (instance) (pg_stat_activity_count) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL has too many connections"
          description: "PostgreSQL instance {{ $labels.instance }} has {{ $value }} connections"