---
# Pod Security Policy for Claude Configuration System
# Enforces security best practices at the pod level
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: claude-config-psp
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'
    apparmor.security.beta.kubernetes.io/allowedProfileNames: 'runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName: 'runtime/default'
    apparmor.security.beta.kubernetes.io/defaultProfileName: 'runtime/default'
spec:
  # Privilege Escalation
  privileged: false
  allowPrivilegeEscalation: false
  
  # Required to prevent privilege escalation
  requiredDropCapabilities:
    - ALL
  
  # Volumes
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  
  # Host features
  hostNetwork: false
  hostIPC: false
  hostPID: false
  
  # Run as non-root user
  runAsUser:
    rule: 'MustRunAsNonRoot'
  
  # SELinux
  seLinux:
    rule: 'RunAsAny'
  
  # Supplemental Groups
  supplementalGroups:
    rule: 'RunAsAny'
  
  # FSGroup
  fsGroup:
    rule: 'RunAsAny'
  
  # Read-only root filesystem
  readOnlyRootFilesystem: true

---
# ClusterRole for PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: claude-config-psp-user
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - claude-config-psp

---
# ClusterRoleBinding for PSP
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: claude-config-psp-binding
roleRef:
  kind: ClusterRole
  name: claude-config-psp-user
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: claude-config-sa
    namespace: claude-config
  - kind: Group
    name: system:serviceaccounts:claude-config
    apiGroup: rbac.authorization.k8s.io