#!/bin/bash
# GitHub Secrets Setup Helper
# Since PAT doesn't have secrets scope, this script provides the values to manually add

echo "======================================"
echo "GitHub Secrets Setup for Candlefish AI"
echo "======================================"
echo ""
echo "Please add these secrets to your GitHub repository:"
echo "https://github.com/candlefish-ai/candlefish-ai/settings/secrets/actions"
echo ""
echo "1. NETLIFY_AUTH_TOKEN"
echo "   Value: nfp_hqTYqLstZ9xg7JLzYhvL6qtZTRR8Hp1g4fd9"
echo ""
echo "2. NETLIFY_SITE_ID_CANDLEFISH"
echo "   Value: cc1ba327-7514-4da6-9d02-d8839eb092d4"
echo ""
echo "3. NETLIFY_SITE_ID_HIGHLINE"  
echo "   Value: 265474aa-9c2a-4db8-8b62-97afb5de02b3"
echo ""
echo "Alternative: Using GitHub CLI with browser authentication:"
echo ""
echo "# First, logout current session"
echo "gh auth logout"
echo ""
echo "# Login with browser (this will grant full permissions)"
echo "gh auth login"
echo ""
echo "# Then run these commands:"
echo "echo 'nfp_hqTYqLstZ9xg7JLzYhvL6qtZTRR8Hp1g4fd9' | gh secret set NETLIFY_AUTH_TOKEN --repo candlefish-ai/candlefish-ai"
echo "echo 'cc1ba327-7514-4da6-9d02-d8839eb092d4' | gh secret set NETLIFY_SITE_ID_CANDLEFISH --repo candlefish-ai/candlefish-ai"
echo "echo '265474aa-9c2a-4db8-8b62-97afb5de02b3' | gh secret set NETLIFY_SITE_ID_HIGHLINE --repo candlefish-ai/candlefish-ai"
echo ""
echo "======================================"
echo "After adding secrets, the GitHub Actions workflow will automatically deploy on push to main branch."