# Netlify Configuration for Candlefish.ai Brand Website

[build]
  # Build command for Next.js static export
  command = "npm run export"
  
  # Publish directory for static export
  publish = "out"

[build.environment]
  # Enable Next.js static export
  NEXT_TELEMETRY_DISABLED = "1"
  STATIC_EXPORT = "true"
  NODE_VERSION = "18.17.0"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400, must-revalidate"

# Redirect www to non-www
[[redirects]]
  from = "https://www.candlefish.ai/*"
  to = "https://candlefish.ai/:splat"
  status = 301
  force = true

# Enable Netlify Functions and Edge Functions
[functions]

# Deployment notifications webhook
[[plugins]]
  package = "@netlify/plugin-emails"

# Deploy succeeded webhook for workshop notes
[[deploy.succeeded]]
  endpoint = "/.netlify/functions/workshop-note-deploy"
  
# Environment variables for workshop note emails  
[build.environment.WORKSHOP_NOTES]
  WORKSHOP_NOTE_FROM_EMAIL = "Candlefish Atelier <atelier@candlefish.ai>"
  WORKSHOP_NOTE_REPLY_TO = "workshop@candlefish.ai"
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Edge Functions Configuration
[[edge_functions]]
  path = "/*"
  function = "ab-testing"

[[edge_functions]]
  path = "/api/*"  
  function = "performance-monitor"

# Deployment settings
[deploy]
  # Skip builds if only documentation changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ':(exclude)*.md' ':(exclude)docs/'"

# Build plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    output_path = "lighthouse-results.json"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

# Analytics and Monitoring
[analytics]
  enable = true
  
[analytics.rum]
  enable = true