global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'security-dashboard-backend'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: /metrics

  - job_name: 'security-dashboard-graphql'
    static_configs:
      - targets: ['host.docker.internal:4001']
    metrics_path: /metrics

  - job_name: 'redis'
    static_configs:
      - targets: ['security-redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['security-postgres:5432']